### ISSUE TITLE
Bugs und Verbesserungsvorschläge zur Polizei

### ISSUE THREAD

**Issue by Oberleutnant20** [DaBurnerGermany/DaPublicServices#5]
Folgende Fehler habe ich gefunden und auch einige Verbesserungsvorschläge:

```
Polizei:
    Akten:
    - Anzeigesteller; besser gestellte Anzeigen
    - Geschlossene Anzeigen werden nicht in der Übersicht bei den Antragstellern angezeigt
    - Personen können nicht Gefandet werden
    Eintrag Akten:
    - Informationen zu Art des Eintrags (vllt mittels eines Info Symbols was man anklicken kann): Was ist mit Positiv und Negativ gemeint?
    
    KFZ-Register:
    - Fahrzeugtyp = Fahrzeug?
    - Kennzeichen: Mindestlänge von 8 ist zu viel; besser Ohne Mindestlänge
    Verbesserung:
    - Erweiterung um die Autofarbe

    Verwaltung:
    - Gesetzbücher:
        - Straftat hinzufügen --> Sonstiges Feld als Zwang? besser wäre Optional
     
    Funkverkehr:
    - Einsatzfahrzeuge:
        - Kurzbeschreibung; besser Kennzeichen 
    - Leitstelle:
        - Leistelle --> Leitstelle
        - Wenn Leitstelle besetzt: 'current_control_take' --> Leitstelle übernehmen

    System:
    - Gruppenmanagement; besser Rang Management
    - Unter Rechte Setzen
        - Leistelle --> Leitstelle

    Archiv:
    - Archiveinträge sollten nur löschbar sein mit den dazugehörigen Rechten (Systemadmin only), also unterscheiden beim Gruppenmanagement
```
